-- insert 10 projects, 20 users, and 30 pledges into the database

INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Ceramic ash tray", "Arts & Crafts", 500, "Jan. 1, 2019", "Feb. 1, 2019");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Rock, Paper, Scissors Game", "Games", 1000, "June 2020", "June 2021");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Sterling's Hikes", "Life Goals", 2000, "May 2023", "May 2024");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Woven Basket", "Arts & Crafts", 50, "2025", "2030");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Epic Hide & Seek", "Games", 5000, "2020", "2021");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Tea Cozies, Inc.", "Arts & Crafts", 20000, "2020", "2025");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Retire to Spain", "Life Goals", 500000, "2040", "2060");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Portraits in String", "Arts & Crafts", 400, "2020", "2021");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Build the next Google", "Tech", 5000000, "2019", "2020");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Old Maid Revised", "Games", 100, "2025", "2035");

INSERT INTO users (name, age) VALUES ("Jenny", 39);
INSERT INTO users (name, age) VALUES ("Sterling", 43);
INSERT INTO users (name, age) VALUES ("Lucy", 17);
INSERT INTO users (name, age) VALUES ("Oscar", 14);
INSERT INTO users (name, age) VALUES ("Juju", 3);
INSERT INTO users (name, age) VALUES ("Marsha", 40);
INSERT INTO users (name, age) VALUES ("Jan", 29);
INSERT INTO users (name, age) VALUES ("Cindy", 45);
INSERT INTO users (name, age) VALUES ("Peter", 37);
INSERT INTO users (name, age) VALUES ("Greg", 90);
INSERT INTO users (name, age) VALUES ("Bobby", 30);
INSERT INTO users (name, age) VALUES ("Mr. Brady", 99);
INSERT INTO users (name, age) VALUES ("Mrs. Brady", 98);
INSERT INTO users (name, age) VALUES ("Cap'n Picard", 100);
INSERT INTO users (name, age) VALUES ("Lt. Riker", 90);
INSERT INTO users (name, age) VALUES ("Dr. Crusher", 50);
INSERT INTO users (name, age) VALUES ("Troi", 35);
INSERT INTO users (name, age) VALUES ("Data", 500);
INSERT INTO users (name, age) VALUES ("Warf", 150);
INSERT INTO users (name, age) VALUES ("Harry Potter", 39);

INSERT INTO pledges (amount, project_id, user_id) VALUES (30, 2, 19);
INSERT INTO pledges (amount, project_id, user_id) VALUES (50, 10, 5);
INSERT INTO pledges (amount, project_id, user_id) VALUES (500, 2, 7);
INSERT INTO pledges (amount, project_id, user_id) VALUES (1000, 6, 15);
INSERT INTO pledges (amount, project_id, user_id) VALUES (5, 1, 3);
INSERT INTO pledges (amount, project_id, user_id) VALUES (100, 7, 13);
INSERT INTO pledges (amount, project_id, user_id) VALUES (10000, 4, 5);
INSERT INTO pledges (amount, project_id, user_id) VALUES (800, 3, 10);
INSERT INTO pledges (amount, project_id, user_id) VALUES (6000, 8, 2);
INSERT INTO pledges (amount, project_id, user_id) VALUES (10, 4, 12);
INSERT INTO pledges (amount, project_id, user_id) VALUES (15, 5, 14);
INSERT INTO pledges (amount, project_id, user_id) VALUES (200, 9, 1);
INSERT INTO pledges (amount, project_id, user_id) VALUES (5000, 13, 4);
INSERT INTO pledges (amount, project_id, user_id) VALUES (900, 3, 6);
INSERT INTO pledges (amount, project_id, user_id) VALUES (555, 4, 6);
INSERT INTO pledges (amount, project_id, user_id) VALUES (300, 2, 6);
INSERT INTO pledges (amount, project_id, user_id) VALUES (150, 7, 8);
INSERT INTO pledges (amount, project_id, user_id) VALUES (99, 8, 18);
INSERT INTO pledges (amount, project_id, user_id) VALUES (20, 10, 17);
INSERT INTO pledges (amount, project_id, user_id) VALUES (50, 2, 16);
INSERT INTO pledges (amount, project_id, user_id) VALUES (100, 4, 20);
INSERT INTO pledges (amount, project_id, user_id) VALUES (50000, 6, 12);
INSERT INTO pledges (amount, project_id, user_id) VALUES (50, 8, 2);
INSERT INTO pledges (amount, project_id, user_id) VALUES (600, 9, 11);
INSERT INTO pledges (amount, project_id, user_id) VALUES (65, 3, 10);
INSERT INTO pledges (amount, project_id, user_id) VALUES (5000, 4, 7);
INSERT INTO pledges (amount, project_id, user_id) VALUES (45, 2, 11);
INSERT INTO pledges (amount, project_id, user_id) VALUES (45, 3, 11);
INSERT INTO pledges (amount, project_id, user_id) VALUES (45, 5, 11);
INSERT INTO pledges (amount, project_id, user_id) VALUES (750, 4, 13);
